### PR TITLE
Make HDFS operations work parallel

### PR DESCRIPTION
**Pull request by joshuayao**
Make HDFS operations work parallel as requested in issue#20

### CODE REVIEW

**Comment by Michael-Frank** [comment]
see discussion: https://github.com/intel-hadoop/Big-Bench/issues/20

**Comment by bdgowda1** [comment]
Josh- do you still want to have this PR open? if not can you please close it.

**Comment by bdgowda1** [comment]
@joshuayao Is this pull request still valid?

**Comment by Michael-Frank** [comment]
no further feedback received on this issue.

**Pull request closed without merging**
