### PR TITLE
BigBench will set the query parameter by itself

### PR DESCRIPTION
**Pull request by LifengWang**
Add the queries_temp folder to store the query sql template script.
Before running the real query, BigBench copy the template sql script to the real running folder and replace the query parameters in sql script with the real value.

### CODE REVIEW

**Comment by Manuel-Danisch** [comment]
Hi,

thanks for your patch. I am not really happy though with checking in temporary directories into the repository. I overlooked the code and it seems that you move the original query files to queries_temp, exchange the hive variables and copy the modified version back to the original query directory. This may lead to problems during future development as we always may accidently check in modified q??.sql files. I suggest that we

* leave the structure as it is now
* when a query is run, a temporary file will be created with `mktemp`
* the hive variables in the original query are set with `sed "s/^set .../^set .../g" q??.sql > /tmp/tmp.??????????`
* this new temp file is set as query sql file
* the temp file will be deleted after the query run

This would keep the repository clean because user customizations are done outside of the repository. Is that OK for you?

Best regards,

Manuel

**Comment by LifengWang** [comment]
Thank you for your advise and I have changed the scripts. Please help to kindly review.

**Comment by Manuel-Danisch** [comment]
Hi,

yes this looks much better, although now I'm pretty sure that this patch may introduce some concurrency problems. These init functions are always called when a query is executed. As the driver runs multiple query streams concurrently in the throughput test, we may end in a situation where two (or more) streams run the same query. In that case, we may end up overwriting a halfway updated temp sql file with a fresh copy of the template sql file. I don't know if this may cause serious problems, but it is possible. I will do some tests and look at the code to see how this problem can be avoided.

Best regards,

Manuel

**Comment by bdgowda1** [comment]
@LifengWang @Manuel-Danisch  is this pull request still required?

**Comment by Manuel-Danisch** [comment]
Hi Bhaskar,

I think that the proposed patch will not work. Concurrent execution of the same query would brake things. My original proposal should work:

* leave the structure as it is now
* when a query is run, a temporary file will be created with `mktemp`
* the hive variables in the original query are set with `sed "s/^set .../^set .../g" q??.sql > /tmp/tmp.??????????`
* this new temp file is set as query sql file
* the temp file will be deleted after the query run

With "mktemp" we assure that concurrent queries don't influence each other. Implementing that solution would take same time and lots of testing to be sure that the "grep" and "awk" commands really do the correct thing in every case.

At the moment, I don't think we should spend time on this problem. However, the pull request in its current form can not be merged.

Best regards,

Manuel

**Pull request closed without merging**
